### PR TITLE
Added code for selective nozzle cleaning

### PR DESCRIPTION
**Pull request by limited660**
Use "M100 T1" to clean extruder 1 and "M100 T2" to clean extruder 2 on 2.0/2.0A printers, "M100" or anything other than "M100 T1" or "M100 T2" will clean both.

### CODE REVIEW

**Comment by limited660** [comment]
Ok, everything is ready to go.  Could not use uint8_t, had to use int8_t for the negative.

**Comment by luc-github** [comment]
did you find the reason why you cannot use 0 for extruder 1 before ?

**Comment by limited660** [comment]
Yeah, I pulled a stupid...forgot to change the values in Printer.cpp

**Comment by luc-github** [comment]
OK - always good to know the root cause for next time ^_^

**Comment by luc-github** [comment]
merged - thank you

**Pull request merged**
