### PR TITLE
Version 0.92.2

### PR DESCRIPTION
**Pull request by Doudou14**
-New commands G10,G11,M200,M209,M600,M355,M360
-Fix
showconfig does not work
Not tested

### CODE REVIEW

**Comment by luc-github** [comment]
Will check this this week end or next week as seems need to do manually and I am busy this week designing part and fully using printer - so I cannot test neither

**Comment by Doudou14** [comment]
I put the firmware on my printer, it works well but I have not tested the controls.
What are these commands? Sli3r is not in use?

**Comment by luc-github** [comment]
They are retractation commands - you may need to do check in repetier if EEPROM is well updated with new values for retractation
seems user by Slic3r per garry feedback
I need also to see how to test it honestly as it is new for me also

**Comment by luc-github** [comment]
Import from 0.92.2 and later done - futur import should be easier as I clearly highlighted  all Davinci Changes.
please refer from https://github.com/luc-github/Repetier-Firmware-0.92/commit/78a45d94b1f597cdf2deedb59553d9a3b04077e7

**Pull request closed without merging**
